### Creating a new report
POST http://localhost:3000/reports
content-type: application/json

{
    "make": "toyota",
    "model": "supra",
    "year": 1994,
    "mileage": 100000,
    "lng": 0,
    "lat": 0,
    "salesPrice": 25000
}